// scripts/write-config.js
const fs = require("fs");
const path = require("path");

// Load .env file into process.env
require("dotenv").config();

const space = process.env.CONTENTFUL_SPACE_ID || "";
const token = process.env.CONTENTFUL_ACCESS_TOKEN || "";

const content = `// Auto-generated by scripts/write-config.js
window.CONTENTFUL_SPACE_ID = ${JSON.stringify(space)};
window.CONTENTFUL_ACCESS_TOKEN = ${JSON.stringify(token)};
`;

const outPath = path.join(__dirname, "..", "assets", "js", "contentful-config.js");
fs.writeFileSync(outPath, content, "utf8");

console.log("✅ Wrote", outPath);
if (!space || !token) {
  console.warn("⚠️ WARNING: Missing env vars");
}
